import { GraphNode, GraphEdge } from '../types/graph'

export const INITIAL_NODES: GraphNode[] = [
  {
    id: 'proj-1',
    title: 'Launch Graph2Do SaaS',
    description: 'Next-generation knowledge graph task management with AI pair-copilot.',
    nodeType: 'project',
    completed: false,
    status: 'in_progress',
    estimatedHours: 42,
    deadline: '2026-10-15',
    parentId: null,
    position: { x: 380, y: 180 },
    isExpanded: true,
    blockers: [],
    dependencies: [],
  },
  {
    id: 'goal-1',
    title: 'Visual Graph Canvas',
    description: 'Interactive SVG sequential graph with circular nodes and progress rings.',
    nodeType: 'goal',
    completed: true,
    status: 'completed',
    estimatedHours: 12,
    deadline: '2026-09-20',
    parentId: 'proj-1',
    stepOrder: 1,
    position: { x: 180, y: 380 },
    isExpanded: false,
    blockers: [],
    dependencies: [],
  },
  {
    id: 'subtask-1-1',
    title: 'Circular Node Component & Progress Bar',
    description: 'SVG stroke-dasharray progress ring for project and goal nodes.',
    nodeType: 'subtask',
    completed: true,
    status: 'completed',
    estimatedHours: 4,
    deadline: '2026-09-18',
    parentId: 'goal-1',
    stepOrder: 1,
    position: { x: 100, y: 520 },
    blockers: [],
    dependencies: [],
  },
  {
    id: 'subtask-1-2',
    title: 'Collapsible Sequential Trees',
    description: 'Group atomic subtasks and hide from high-level view by default.',
    nodeType: 'subtask',
    completed: true,
    status: 'completed',
    estimatedHours: 4,
    deadline: '2026-09-19',
    parentId: 'goal-1',
    stepOrder: 2,
    position: { x: 260, y: 520 },
    blockers: [],
    dependencies: ['subtask-1-1'],
  },
  {
    id: 'goal-2',
    title: 'AI Copilot & Chat Panel',
    description: 'Conversational agent aware of graph structure, selected context, and deadlines.',
    nodeType: 'goal',
    completed: false,
    status: 'in_progress',
    estimatedHours: 16,
    deadline: '2026-09-28',
    parentId: 'proj-1',
    stepOrder: 2,
    position: { x: 580, y: 380 },
    isExpanded: true,
    blockers: [],
    dependencies: ['goal-1'],
  },
  {
    id: 'subtask-2-1',
    title: 'Contextual Selection Injection',
    description: 'Clicking any node injects it as context for prompt commands.',
    nodeType: 'subtask',
    completed: true,
    status: 'completed',
    estimatedHours: 5,
    deadline: '2026-09-22',
    parentId: 'goal-2',
    stepOrder: 1,
    position: { x: 480, y: 520 },
    blockers: [],
    dependencies: ['goal-1'],
  },
  {
    id: 'subtask-2-2',
    title: 'Automatic Goal Decomposition',
    description: 'AI generates linked atomic subtasks on command with estimated hours.',
    nodeType: 'subtask',
    completed: false,
    status: 'in_progress',
    estimatedHours: 6,
    deadline: '2026-09-25',
    parentId: 'goal-2',
    stepOrder: 2,
    position: { x: 680, y: 520 },
    blockers: [],
    dependencies: ['subtask-2-1'],
  },
  {
    id: 'proj-2',
    title: 'Cloud Infrastructure & Kinde Auth',
    description: 'FastAPI backend, PostgreSQL Alembic migrations, and OAuth 2.0 security.',
    nodeType: 'project',
    completed: false,
    status: 'blocked',
    estimatedHours: 14,
    deadline: '2026-10-02',
    parentId: null,
    position: { x: 920, y: 220 },
    isExpanded: false,
    blockers: ['subtask-2-2'],
    dependencies: ['proj-1'],
  },
]

export const INITIAL_EDGES: GraphEdge[] = [
  { id: 'e-p1-g1', sourceId: 'proj-1', targetId: 'goal-1', label: 'contains', edgeType: 'hierarchy' },
  { id: 'e-p1-g2', sourceId: 'proj-1', targetId: 'goal-2', label: 'contains', edgeType: 'hierarchy' },
  { id: 'e-g1-s1', sourceId: 'goal-1', targetId: 'subtask-1-1', label: 'subtask', edgeType: 'hierarchy' },
  { id: 'e-g1-s2', sourceId: 'goal-1', targetId: 'subtask-1-2', label: 'subtask', edgeType: 'hierarchy' },
  { id: 'e-s1-s2', sourceId: 'subtask-1-1', targetId: 'subtask-1-2', label: 'sequence', edgeType: 'sequence' },
  { id: 'e-g1-g2', sourceId: 'goal-1', targetId: 'goal-2', label: 'depends on', edgeType: 'sequence' },
  { id: 'e-g2-s1', sourceId: 'goal-2', targetId: 'subtask-2-1', label: 'subtask', edgeType: 'hierarchy' },
  { id: 'e-g2-s2', sourceId: 'goal-2', targetId: 'subtask-2-2', label: 'subtask', edgeType: 'hierarchy' },
  { id: 'e-s21-s22', sourceId: 'subtask-2-1', targetId: 'subtask-2-2', label: 'sequence', edgeType: 'sequence' },
  { id: 'e-p1-p2', sourceId: 'proj-1', targetId: 'proj-2', label: 'blocks', edgeType: 'dependency' },
]
